# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/harrison/Programming/PhysicsEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/harrison/Programming/PhysicsEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/harrison/Programming/PhysicsEngine/CMakeFiles /home/harrison/Programming/PhysicsEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/harrison/Programming/PhysicsEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PhysicsEngine

# Build rule for target.
PhysicsEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PhysicsEngine
.PHONY : PhysicsEngine

# fast build rule for target.
PhysicsEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/build
.PHONY : PhysicsEngine/fast

src/Engine.o: src/Engine.cpp.o

.PHONY : src/Engine.o

# target to build an object file
src/Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/Engine.cpp.o
.PHONY : src/Engine.cpp.o

src/Engine.i: src/Engine.cpp.i

.PHONY : src/Engine.i

# target to preprocess a source file
src/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/Engine.cpp.i
.PHONY : src/Engine.cpp.i

src/Engine.s: src/Engine.cpp.s

.PHONY : src/Engine.s

# target to generate assembly for a file
src/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/Engine.cpp.s
.PHONY : src/Engine.cpp.s

src/Renderer/Mesh.o: src/Renderer/Mesh.cpp.o

.PHONY : src/Renderer/Mesh.o

# target to build an object file
src/Renderer/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/Renderer/Mesh.cpp.o
.PHONY : src/Renderer/Mesh.cpp.o

src/Renderer/Mesh.i: src/Renderer/Mesh.cpp.i

.PHONY : src/Renderer/Mesh.i

# target to preprocess a source file
src/Renderer/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/Renderer/Mesh.cpp.i
.PHONY : src/Renderer/Mesh.cpp.i

src/Renderer/Mesh.s: src/Renderer/Mesh.cpp.s

.PHONY : src/Renderer/Mesh.s

# target to generate assembly for a file
src/Renderer/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/Renderer/Mesh.cpp.s
.PHONY : src/Renderer/Mesh.cpp.s

src/Renderer/Renderer.o: src/Renderer/Renderer.cpp.o

.PHONY : src/Renderer/Renderer.o

# target to build an object file
src/Renderer/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/Renderer/Renderer.cpp.o
.PHONY : src/Renderer/Renderer.cpp.o

src/Renderer/Renderer.i: src/Renderer/Renderer.cpp.i

.PHONY : src/Renderer/Renderer.i

# target to preprocess a source file
src/Renderer/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/Renderer/Renderer.cpp.i
.PHONY : src/Renderer/Renderer.cpp.i

src/Renderer/Renderer.s: src/Renderer/Renderer.cpp.s

.PHONY : src/Renderer/Renderer.s

# target to generate assembly for a file
src/Renderer/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/Renderer/Renderer.cpp.s
.PHONY : src/Renderer/Renderer.cpp.s

src/imgui/imgui.o: src/imgui/imgui.cpp.o

.PHONY : src/imgui/imgui.o

# target to build an object file
src/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui.cpp.o
.PHONY : src/imgui/imgui.cpp.o

src/imgui/imgui.i: src/imgui/imgui.cpp.i

.PHONY : src/imgui/imgui.i

# target to preprocess a source file
src/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui.cpp.i
.PHONY : src/imgui/imgui.cpp.i

src/imgui/imgui.s: src/imgui/imgui.cpp.s

.PHONY : src/imgui/imgui.s

# target to generate assembly for a file
src/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui.cpp.s
.PHONY : src/imgui/imgui.cpp.s

src/imgui/imgui_demo.o: src/imgui/imgui_demo.cpp.o

.PHONY : src/imgui/imgui_demo.o

# target to build an object file
src/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_demo.cpp.o
.PHONY : src/imgui/imgui_demo.cpp.o

src/imgui/imgui_demo.i: src/imgui/imgui_demo.cpp.i

.PHONY : src/imgui/imgui_demo.i

# target to preprocess a source file
src/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_demo.cpp.i
.PHONY : src/imgui/imgui_demo.cpp.i

src/imgui/imgui_demo.s: src/imgui/imgui_demo.cpp.s

.PHONY : src/imgui/imgui_demo.s

# target to generate assembly for a file
src/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_demo.cpp.s
.PHONY : src/imgui/imgui_demo.cpp.s

src/imgui/imgui_draw.o: src/imgui/imgui_draw.cpp.o

.PHONY : src/imgui/imgui_draw.o

# target to build an object file
src/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_draw.cpp.o
.PHONY : src/imgui/imgui_draw.cpp.o

src/imgui/imgui_draw.i: src/imgui/imgui_draw.cpp.i

.PHONY : src/imgui/imgui_draw.i

# target to preprocess a source file
src/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_draw.cpp.i
.PHONY : src/imgui/imgui_draw.cpp.i

src/imgui/imgui_draw.s: src/imgui/imgui_draw.cpp.s

.PHONY : src/imgui/imgui_draw.s

# target to generate assembly for a file
src/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_draw.cpp.s
.PHONY : src/imgui/imgui_draw.cpp.s

src/imgui/imgui_impl_glfw.o: src/imgui/imgui_impl_glfw.cpp.o

.PHONY : src/imgui/imgui_impl_glfw.o

# target to build an object file
src/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_impl_glfw.cpp.o
.PHONY : src/imgui/imgui_impl_glfw.cpp.o

src/imgui/imgui_impl_glfw.i: src/imgui/imgui_impl_glfw.cpp.i

.PHONY : src/imgui/imgui_impl_glfw.i

# target to preprocess a source file
src/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_impl_glfw.cpp.i
.PHONY : src/imgui/imgui_impl_glfw.cpp.i

src/imgui/imgui_impl_glfw.s: src/imgui/imgui_impl_glfw.cpp.s

.PHONY : src/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
src/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_impl_glfw.cpp.s
.PHONY : src/imgui/imgui_impl_glfw.cpp.s

src/imgui/imgui_impl_opengl3.o: src/imgui/imgui_impl_opengl3.cpp.o

.PHONY : src/imgui/imgui_impl_opengl3.o

# target to build an object file
src/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_impl_opengl3.cpp.o
.PHONY : src/imgui/imgui_impl_opengl3.cpp.o

src/imgui/imgui_impl_opengl3.i: src/imgui/imgui_impl_opengl3.cpp.i

.PHONY : src/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
src/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_impl_opengl3.cpp.i
.PHONY : src/imgui/imgui_impl_opengl3.cpp.i

src/imgui/imgui_impl_opengl3.s: src/imgui/imgui_impl_opengl3.cpp.s

.PHONY : src/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
src/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_impl_opengl3.cpp.s
.PHONY : src/imgui/imgui_impl_opengl3.cpp.s

src/imgui/imgui_widgets.o: src/imgui/imgui_widgets.cpp.o

.PHONY : src/imgui/imgui_widgets.o

# target to build an object file
src/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_widgets.cpp.o
.PHONY : src/imgui/imgui_widgets.cpp.o

src/imgui/imgui_widgets.i: src/imgui/imgui_widgets.cpp.i

.PHONY : src/imgui/imgui_widgets.i

# target to preprocess a source file
src/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_widgets.cpp.i
.PHONY : src/imgui/imgui_widgets.cpp.i

src/imgui/imgui_widgets.s: src/imgui/imgui_widgets.cpp.s

.PHONY : src/imgui/imgui_widgets.s

# target to generate assembly for a file
src/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/imgui/imgui_widgets.cpp.s
.PHONY : src/imgui/imgui_widgets.cpp.s

src/implot/implot.o: src/implot/implot.cpp.o

.PHONY : src/implot/implot.o

# target to build an object file
src/implot/implot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/implot/implot.cpp.o
.PHONY : src/implot/implot.cpp.o

src/implot/implot.i: src/implot/implot.cpp.i

.PHONY : src/implot/implot.i

# target to preprocess a source file
src/implot/implot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/implot/implot.cpp.i
.PHONY : src/implot/implot.cpp.i

src/implot/implot.s: src/implot/implot.cpp.s

.PHONY : src/implot/implot.s

# target to generate assembly for a file
src/implot/implot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/implot/implot.cpp.s
.PHONY : src/implot/implot.cpp.s

src/implot/implot_demo.o: src/implot/implot_demo.cpp.o

.PHONY : src/implot/implot_demo.o

# target to build an object file
src/implot/implot_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/implot/implot_demo.cpp.o
.PHONY : src/implot/implot_demo.cpp.o

src/implot/implot_demo.i: src/implot/implot_demo.cpp.i

.PHONY : src/implot/implot_demo.i

# target to preprocess a source file
src/implot/implot_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/implot/implot_demo.cpp.i
.PHONY : src/implot/implot_demo.cpp.i

src/implot/implot_demo.s: src/implot/implot_demo.cpp.s

.PHONY : src/implot/implot_demo.s

# target to generate assembly for a file
src/implot/implot_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/implot/implot_demo.cpp.s
.PHONY : src/implot/implot_demo.cpp.s

src/implot/implot_items.o: src/implot/implot_items.cpp.o

.PHONY : src/implot/implot_items.o

# target to build an object file
src/implot/implot_items.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/implot/implot_items.cpp.o
.PHONY : src/implot/implot_items.cpp.o

src/implot/implot_items.i: src/implot/implot_items.cpp.i

.PHONY : src/implot/implot_items.i

# target to preprocess a source file
src/implot/implot_items.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/implot/implot_items.cpp.i
.PHONY : src/implot/implot_items.cpp.i

src/implot/implot_items.s: src/implot/implot_items.cpp.s

.PHONY : src/implot/implot_items.s

# target to generate assembly for a file
src/implot/implot_items.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/implot/implot_items.cpp.s
.PHONY : src/implot/implot_items.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tools/MeshHelper.o: src/tools/MeshHelper.cpp.o

.PHONY : src/tools/MeshHelper.o

# target to build an object file
src/tools/MeshHelper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/tools/MeshHelper.cpp.o
.PHONY : src/tools/MeshHelper.cpp.o

src/tools/MeshHelper.i: src/tools/MeshHelper.cpp.i

.PHONY : src/tools/MeshHelper.i

# target to preprocess a source file
src/tools/MeshHelper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/tools/MeshHelper.cpp.i
.PHONY : src/tools/MeshHelper.cpp.i

src/tools/MeshHelper.s: src/tools/MeshHelper.cpp.s

.PHONY : src/tools/MeshHelper.s

# target to generate assembly for a file
src/tools/MeshHelper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/tools/MeshHelper.cpp.s
.PHONY : src/tools/MeshHelper.cpp.s

src/tools/Shader.o: src/tools/Shader.cpp.o

.PHONY : src/tools/Shader.o

# target to build an object file
src/tools/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/tools/Shader.cpp.o
.PHONY : src/tools/Shader.cpp.o

src/tools/Shader.i: src/tools/Shader.cpp.i

.PHONY : src/tools/Shader.i

# target to preprocess a source file
src/tools/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/tools/Shader.cpp.i
.PHONY : src/tools/Shader.cpp.i

src/tools/Shader.s: src/tools/Shader.cpp.s

.PHONY : src/tools/Shader.s

# target to generate assembly for a file
src/tools/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/tools/Shader.cpp.s
.PHONY : src/tools/Shader.cpp.s

src/tools/Texture.o: src/tools/Texture.cpp.o

.PHONY : src/tools/Texture.o

# target to build an object file
src/tools/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/tools/Texture.cpp.o
.PHONY : src/tools/Texture.cpp.o

src/tools/Texture.i: src/tools/Texture.cpp.i

.PHONY : src/tools/Texture.i

# target to preprocess a source file
src/tools/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/tools/Texture.cpp.i
.PHONY : src/tools/Texture.cpp.i

src/tools/Texture.s: src/tools/Texture.cpp.s

.PHONY : src/tools/Texture.s

# target to generate assembly for a file
src/tools/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/tools/Texture.cpp.s
.PHONY : src/tools/Texture.cpp.s

src/tools/Timer.o: src/tools/Timer.cpp.o

.PHONY : src/tools/Timer.o

# target to build an object file
src/tools/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/tools/Timer.cpp.o
.PHONY : src/tools/Timer.cpp.o

src/tools/Timer.i: src/tools/Timer.cpp.i

.PHONY : src/tools/Timer.i

# target to preprocess a source file
src/tools/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/tools/Timer.cpp.i
.PHONY : src/tools/Timer.cpp.i

src/tools/Timer.s: src/tools/Timer.cpp.s

.PHONY : src/tools/Timer.s

# target to generate assembly for a file
src/tools/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysicsEngine.dir/build.make CMakeFiles/PhysicsEngine.dir/src/tools/Timer.cpp.s
.PHONY : src/tools/Timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PhysicsEngine"
	@echo "... src/Engine.o"
	@echo "... src/Engine.i"
	@echo "... src/Engine.s"
	@echo "... src/Renderer/Mesh.o"
	@echo "... src/Renderer/Mesh.i"
	@echo "... src/Renderer/Mesh.s"
	@echo "... src/Renderer/Renderer.o"
	@echo "... src/Renderer/Renderer.i"
	@echo "... src/Renderer/Renderer.s"
	@echo "... src/imgui/imgui.o"
	@echo "... src/imgui/imgui.i"
	@echo "... src/imgui/imgui.s"
	@echo "... src/imgui/imgui_demo.o"
	@echo "... src/imgui/imgui_demo.i"
	@echo "... src/imgui/imgui_demo.s"
	@echo "... src/imgui/imgui_draw.o"
	@echo "... src/imgui/imgui_draw.i"
	@echo "... src/imgui/imgui_draw.s"
	@echo "... src/imgui/imgui_impl_glfw.o"
	@echo "... src/imgui/imgui_impl_glfw.i"
	@echo "... src/imgui/imgui_impl_glfw.s"
	@echo "... src/imgui/imgui_impl_opengl3.o"
	@echo "... src/imgui/imgui_impl_opengl3.i"
	@echo "... src/imgui/imgui_impl_opengl3.s"
	@echo "... src/imgui/imgui_widgets.o"
	@echo "... src/imgui/imgui_widgets.i"
	@echo "... src/imgui/imgui_widgets.s"
	@echo "... src/implot/implot.o"
	@echo "... src/implot/implot.i"
	@echo "... src/implot/implot.s"
	@echo "... src/implot/implot_demo.o"
	@echo "... src/implot/implot_demo.i"
	@echo "... src/implot/implot_demo.s"
	@echo "... src/implot/implot_items.o"
	@echo "... src/implot/implot_items.i"
	@echo "... src/implot/implot_items.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tools/MeshHelper.o"
	@echo "... src/tools/MeshHelper.i"
	@echo "... src/tools/MeshHelper.s"
	@echo "... src/tools/Shader.o"
	@echo "... src/tools/Shader.i"
	@echo "... src/tools/Shader.s"
	@echo "... src/tools/Texture.o"
	@echo "... src/tools/Texture.i"
	@echo "... src/tools/Texture.s"
	@echo "... src/tools/Timer.o"
	@echo "... src/tools/Timer.i"
	@echo "... src/tools/Timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

